# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 14:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_type', models.CharField(max_length=100)),
                ('bill_cost', models.FloatField()),
                ('bill_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Dependente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DependenteConta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contaID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Conta')),
                ('dependenteID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Dependente')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('age', models.DateField()),
                ('user_create_date', models.DateField(auto_now_add=True)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, default='', max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(blank=True, max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioTeste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='dependente',
            name='usuarioID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Usuario'),
        ),
        migrations.AddField(
            model_name='conta',
            name='usuarioID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Usuario'),
        ),
    ]
