# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conta',
            name='bill_create_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='conta',
            name='bill_desc',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
